[project]
name = "day14"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "matrix-1407", email = "mrudulbokade1407@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "groq>=1.6.0",
    "numpy>=2.4.6",
    "pandas>=3.0.5",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.3",
    "qdrant-client>=1.19.0",
    "sentence-transformers>=6.0.0",
]

[project.scripts]
day14 = "day14:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
